---
title: "linear_models"
author: "Paula Wu"
date: "11/16/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

Load NYC Airbnb dataset
```{r}
data("nyc_airbnb")
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location/2) %>% 
  rename(
    borough = neighbourhood_group
  ) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighbourhood, room_type)

```

Let's do some visualization
```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price)) + 
  geom_point()
```

Let's fit a linear model
```{r}
fit = lm(price~stars+borough, data = nyc_airbnb)
```

Let's take a look at this...
```{r}
summary(fit)
summary(fit)$coef
```

If you want to present output...
```{r}
fit %>% 
  broom::tidy() %>%  # turn into a dataframe
  mutate(term = str_replace(term, "borough", "Borough: ")) %>% 
  select(term, estimate, p.value)
```

## Diagnostics
```{r}
resid(fit)  # not a good way to get the residuals

modelr::add_residuals(nyc_airbnb, fit) %>%   # a dataframe containing the residuals
  ggplot(aes(x = stars, y = resid))+
  geom_point()

modelr::add_residuals(nyc_airbnb, fit) %>%   # a dataframe containing the residuals
  ggplot(aes(x = resid))+
  geom_density()+
  xlim(-200,200)
```

## Interaction? Nesting?

Let's try a different model
```{r}
fit = lm(price ~ stars + room_type, data = nyc_airbnb)

broom::tidy(fit)
```

Let's try nesting...
```{r}
nyc_airbnb %>% 
  relocate(borough) %>% 
  nest(data = price:room_type) %>% 
  mutate(
    lm_fits = map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
    lm_results = map(lm_fits, broom::tidy)) %>% 
  select(borough, lm_results) %>% 
  unnest(lm_results) %>% 
  filter(term == "stars")
```

Look at neighborhoods in Manhattan...
```{r}
manhattan_lm_results_df =
  nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  select(-borough) %>% 
  relocate(neighbourhood) %>% 
  nest(data = price:room_type) %>% 
  mutate(
    lm_fits = map(.x = data, ~lm(price~ stars+room_type, data = .x)),
    lm_results = map(lm_fits, broom::tidy)
  ) %>% 
  select(neighbourhood, lm_results) %>% 
  unnest(lm_results)

manhattan_lm_results_df %>% 
  filter(term == "stars") %>% 
  ggplot(aes(x = estimate))+
  geom_density()

manhattan_lm_results_df %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighbourhood, y = estimate))+
  geom_point() +
  facet_grid(~term) +
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
```

## logistic regression
```{r}
new_nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(expensive_apt = as.numeric(price>500))
```


Let's fit a logistic regression for the binary outcome
```{r}
logistic_fit = 
  glm(
    expensive_apt ~ stars + borough, 
    data = new_nyc_airbnb, 
    family = binomial())
logistic_fit %>% 
  broom::tidy() %>% 
  mutate(
    term = str_replace(term, "borough", "Borough: "),
    estimate = exp(estimate)  # odds ratio: by exponentiation
  ) %>% 
  select(term, OR = estimate, p.value)

new_nyc_airbnb %>% 
  modelr::add_predictions(logistic_fit) %>% 
  mutate(pred = boot::inv.logit(pred))  # change to probability
```


